<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:its="http://www.w3.org/2005/11/its"
    xmlns="http://www.tei-c.org/ns/1.0" xmlns:tei="http://www.tei-c.org/ns/1.0"
    exclude-result-prefixes="xd xs its my tei" version="2.0"
    xmlns:my="local-functions.uri">
    <xsl:output method="html" indent="yes" encoding="UTF-8"/>
    <!-- Receives a document generated by aggregation that has <div> top element and <my:struct> for index of ref.xml 
        and <my:composList> for composite index of all witnesses -->

    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>Test Dropdown</title>
                <style type="text/css">
                    .sub2{
                        color:black;
                    }
                    .sub3{
                        padding-left:3em;
                        font-style:italic;
                    }
                    .sub4{
                        padding-left:4em;
                    }</style>
            </head>
            <body>
                <div class="dropdown">
                    <p>Select from the following</p>
                    <ul>
                        <xsl:apply-templates/>
                    </ul>
                </div>
            </body>

        </html>
    </xsl:template>
    <xsl:template match="div|my:struct">
        <xsl:apply-templates/>
    </xsl:template>
    <xsl:template match="my:wits">
        <xsl:apply-templates/>
    </xsl:template>
    <xsl:template match="my:order">
        <li xmlns="http://www.w3.org/1999/xhtml">
            <xsl:value-of select="@n"/>
            <xsl:apply-templates/>
        </li>
    </xsl:template>
    <xsl:template match="my:tract">
        <ul><li xmlns="http://www.w3.org/1999/xhtml">
            <xsl:value-of select="replace(@n,'_',' ')"/>
            <xsl:if
                test="substring-after(@xml:id,'ref.') = //my:tract-compos/@n">
                <ul>
                    <xsl:apply-templates/>
                </ul>
            </xsl:if>
        </li></ul>
    </xsl:template>
    <xsl:template match="my:chapter">
        <li xmlns="http://www.w3.org/1999/xhtml">Chapter <xsl:value-of
                select="substring-after(@xml:id, concat(parent::my:tract/@xml:id, '.'))"/>
            <xsl:if test="substring-after(@xml:id,'ref.') = //my:ch-compos/@n">
                <!--<ul><xsl:apply-templates/></ul>-->
            </xsl:if></li>
    </xsl:template>
    <xsl:template match="my:composList"/>
</xsl:stylesheet>
